### PR TITLE
Land Acknowledgement  Added

### PR DESCRIPTION
**Pull request by KevinGarvey**
Added a Land Acknowledgement page per Stefan Ballmer

https://gold-monah-87.tiiny.site

### CODE REVIEW

**Comment by ahnitz** [comment]
@KevinGarvey There appears to have been a right parenthesis inserted at the end of each paragraph. There is maybe also an extra newline.

**Comment by KevinGarvey** [comment]
Correcting

**Comment by ahnitz** [comment]
@KevinGarvey FYI, you don't need to close. Just add another commit to the branch that fixes the issue (or updates the page) and push the updated version. The PR tracks the branch, so whatever it's state is currently is reflected.

**Comment by KevinGarvey** [comment]
Thanks!  That has been corrected

**Pull request merged**
