### PR TITLE
Update Job Postings

### PR DESCRIPTION
**Pull request by KevinGarvey**
https://gold-monah-87.tiiny.site/

### CODE REVIEW

**Comment by KevinGarvey** [comment]
I had to mess with the nav bar working a bit in order to get it to fit.  let me know if thats an issue

**Comment by ahnitz** [comment]
@KevinGarvey I think the navbar changes are fine. There's some conflicts you need to resolve though which prevent his from being merged.

**Comment by KevinGarvey** [comment]
I'm not sure what the issue is... basically the entire job postings page is creating a conflict.  Let me try to isolate it

**Comment by ahnitz** [comment]
@KevinGarvey If you know which version of the file you want, resolving it is pretty easy.

**Pull request closed without merging**
