### PR TITLE
Create Jobs Page

### PR DESCRIPTION
**Pull request by KevinGarvey**
https://gold-monah-87.tiiny.site/index.html#intro

### CODE REVIEW

**Comment by ahnitz** [comment]
@KevinGarvey Should we include deadline in the table?

**Comment by ahnitz** [comment]
@KevinGarvey Also, should there be a blurb at the start stating what this page is for?

**Comment by KevinGarvey** [comment]
That's not a bad idea.  Ok let me write something up for a blurb and I will add a deadline column.  If I cannot find a deadline I will put "TBD" or someting

**Comment by KevinGarvey** [comment]
let me know what you think!

**Comment by ahnitz** [comment]
@KevinGarvey I think this is OK, but it would be nice for the table to be better looking. That can be done an improvement though.

**Review by ahnitz — APPROVED** [review]

**Comment by KevinGarvey** [comment]
I agree about the table.  I'm working with some different templates but for now this is just via excel....

**Pull request merged**
